# Generated by Django 4.1 on 2022-08-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(default='Administrator', max_length=20)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('message_language', models.CharField(choices=[('eng', 'English'), ('rus', 'Russian')], max_length=4)),
            ],
            options={
                'verbose_name': 'e-Mail Receiver',
                'verbose_name_plural': 'e-Mail Receivers',
            },
        ),
    ]
