# Generated by Django 4.1 on 2022-08-07 19:11

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrases', messenger.models.ListField(blank=True)),
                ('topic', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to=messenger.models.video_management)),
                ('quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=5)),
                ('screen_size', models.CharField(max_length=10)),
                ('avatar', models.CharField(max_length=10)),
                ('lang', models.CharField(choices=[('eng', 'eng'), ('rus', 'rus')], max_length=10)),
                ('phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.phrases')),
                ('subtitles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.subtitle')),
            ],
        ),
        migrations.AddField(
            model_name='subtitle',
            name='video_file',
            field=models.ManyToManyField(to='messenger.videofiles'),
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=30, unique=True)),
                ('script_related_phrases', models.ManyToManyField(to='messenger.phrases')),
            ],
        ),
        migrations.AddField(
            model_name='phrases',
            name='entry_of_script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='messenger.script'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('anonimous_token', models.TextField()),
                ('reported', models.BooleanField(default=False)),
                ('detected_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='messenger_Message_related_Scheme', to='messenger.phrases')),
            ],
        ),
        migrations.AddConstraint(
            model_name='videofiles',
            constraint=models.UniqueConstraint(fields=('phrase', 'screen_size', 'avatar', 'quality'), name='unique video-file'),
        ),
    ]
