# Generated by Django 4.0.6 on 2022-07-10 16:13

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrases', messenger.models.ListField(blank=True)),
                ('topic', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to=messenger.models.video_management)),
                ('quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=5)),
                ('screen_size', models.CharField(max_length=10)),
                ('avatar', models.CharField(max_length=10)),
                ('lang', models.CharField(max_length=10)),
                ('phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.phrases')),
            ],
        ),
    ]
