# Generated by Django 4.0.6 on 2022-07-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrases',
            name='topic',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='videofiles',
            constraint=models.UniqueConstraint(fields=('phrase', 'screen_size', 'avatar', 'quality'), name='unique video-file'),
        ),
    ]
