# Generated by Django 4.1 on 2022-08-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_phrases_entry_of_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrases',
            name='entry_of_script',
        ),
        migrations.AddField(
            model_name='phrases',
            name='entry_of_scripts',
            field=models.ManyToManyField(to='messenger.script'),
        ),
    ]
