# Generated by Django 4.1 on 2022-08-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_phrases_entry_of_script_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrases',
            name='entry_of_scripts',
            field=models.ManyToManyField(blank=True, to='messenger.script'),
        ),
    ]
