# Generated by Django 4.1 on 2022-08-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_phrases_entry_of_scripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('lang', models.CharField(choices=[('eng', 'eng'), ('rus', 'rus')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='phrases',
            name='buttons',
            field=models.ManyToManyField(blank=True, to='messenger.button'),
        ),
    ]
