# Generated by Django 4.1 on 2022-08-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_button_related_phrases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='related_phrases',
            new_name='button_related_phrases',
        ),
    ]
