# Generated by Django 4.1 on 2022-08-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_rename_related_phrases_button_button_related_phrases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('anonimous_token', models.TextField(unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='anonimous_token',
        ),
        migrations.AlterField(
            model_name='button',
            name='lang',
            field=models.CharField(choices=[('rus', 'rus'), ('eng', 'eng')], max_length=10),
        ),
        migrations.AlterField(
            model_name='videofiles',
            name='lang',
            field=models.CharField(choices=[('rus', 'rus'), ('eng', 'eng')], max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.sender'),
        ),
    ]
