# Generated by Django 4.1 on 2022-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_sender_remove_message_anonimous_token_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videofiles',
            name='unique video-file',
        ),
        migrations.AddConstraint(
            model_name='videofiles',
            constraint=models.UniqueConstraint(fields=('phrase', 'screen_size', 'avatar', 'quality', 'lang'), name='unique video-file'),
        ),
    ]
