# Generated by Django 4.1 on 2022-08-20 19:24

from django.db import migrations
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_remove_videofiles_unique video-file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='topics',
            field=messenger.models.ListField(blank=True, default=''),
        ),
    ]
